# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Backend Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env: 
  JWT_SECRET: ${{secrets.JWT_SECRET}}
  DATABASE_URL: ${{secrets.DATABASE_URL}}
  NODE_ENV: ${{secrets.NODE_ENV}}}
  LOGTAIL_SOURCE_TOKEN: ${{secrets.TEST_LOGTAIL_SOURCE_TOKEN}}
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 19.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Testing with Node ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm test
    - run: npm run build --if-present
    
